; ============================================================
; PlatformIO Configuration — IoT Predictive Maintenance ESP32
; ============================================================
[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; Serial monitor
monitor_speed = 115200

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -DARDUINO_ARCH_ESP32

; Upload settings
upload_speed = 921600

; ---- Libraries ----
lib_deps =
    ; Sensors
    adafruit/Adafruit ADXL345 @ ^1.3.2
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit INA219 @ ^1.2.3
    bogde/HX711 @ ^0.7.5
    adafruit/Adafruit Unified Sensor @ ^1.1.14

    ; Wi-Fi & MQTT (TLS over AWS IoT)
    256dpi/MQTT @ ^2.5.2

    ; NTP time sync
    arduino-libraries/NTPClient @ ^3.2.1

    ; JSON payload building
    bblanchon/ArduinoJson @ ^7.2.1

; Partition scheme — more OTA space
board_build.partitions = min_spiffs.csv
